# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TQmM7_utFzxyqB_cjQTRa2ZXcJMpIX2l

---
## **문제1**
"""

matrix_a = [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]]
matrix_a

def matrix_b(mtx):
    for i in range(0, 3):
        if matrix_a[i][0] == 1 or 5 or 9:
            i = 0
            matrix_a[i+1][0] = 1
            matrix_a[i+2][0] = 5
            matrix_a[i+3][0] = 9

    for i in range(1, 4):
        if matrix_a[0][i] == 2 or 3 or 4:
            i = 0
            matrix_a[0][i] = 2
            matrix_a[0][i+1] = 3
            matrix_a[0][i+2] = 4

    for i in range(1, 4):
        if matrix_a[i][3] == 8 or 12 or 16:
            i = 0
            matrix_a[i][3] = 8
            matrix_a[i+1][3] = 12
            matrix_a[i+2][3] = 16

    for i in range(0, 3):
        if matrix_a[3][i] == 13 or 14 or 15:
            i = 0
            matrix_a[3][i+1] = 13
            matrix_a[3][i+2] = 14
            matrix_a[3][i+3] = 15

    for i in range(1, 3):
        if matrix_a[1][i] == 6 or 7:
            i = 0
            matrix_a[i+1][i+2] = 6
            matrix_a[i+2][i+2] = 7

    
    for i in range(1, 3):
        if matrix_a[2][i] == 10 or 11:
            i = 0
            matrix_a[i+1][i+1] = 10
            matrix_a[i+2][i+1] = 11

    return matrix_a

matrix_b(matrix_a)

def matrix_b(mtx):
    for i in range(0, 4):
        if matrix_a[i][0] == 1 or 5 or 9 or 13:
            matrix_a[1][0] = 1
            matrix_a[2][0] = 5
            matrix_a[3][0] = 9
            matrix_a[3][1] = 13

    for i in range(0, 4):
        if matrix_a[0][i] == 2 or 3 or 4:
            matrix_a[0][0] = 2
            matrix_a[0][1] = 3
            matrix_a[0][2] = 4
    
    for i in range(1, 4):
        if matrix_a[i][3] == 8 or 12 or 16:
            matrix_a[0][3] = 8
            matrix_a[1][3] = 12
            matrix_a[2][3] = 16
    
    for i in range(0, 4):
        if matrix_a[3][i] == 13 or 14 or 15:
            matrix_a[3][1] = 13
            matrix_a[3][2] = 14
            matrix_a[3][3] = 15

    for i in range(1, 3):
        if matrix_a[1][i] == 6 or 7:
            matrix_a[1][2] = 6
            matrix_a[2][2] = 7

    for i in range(1, 3):
        if matrix_a[2][i] == 10 or 11:
            matrix_a[1][1] = 10
            matrix_a[2][1] = 11

    return matrix_a

matrix_b(matrix_a)

"""---
## **문제2**
"""

work_list = [
             "낮음, 1, A.로그인 화면 오타 수정",
             "긴급, 3, B.OTP 사용자 로그인 안됨",
             "보통, 1, C.권한 안내 문구 수정",
             "낮음, 2, D.로딩중 표시 아이콘 변경",
             "긴급, 3, E.메일의 본문이 표시되지 않는 문제",
             "보통, 1, F.첨부파일 사이즈 표시 오류 수정",
             "긴급, 2, G.메일 전송시 첨부파일 누락됨",
             "보통, 3, H.1:1 문의 기능 구현",
             "낮음, 1, I.제품 로고 변경",
             "보통, 3, J.안읽음 카운트 오류 문제 ",
             "낮음, 1, K.폰트 색상 변경 ",
             "긴급, 2, L.전체 메일함 동기화 안되는 문제",
]

work_list_origin = [list(s.split(", ")) for s in work_list]

for i in range(0, len(work_list_origin)):
    work_list_origin[i][1] = int(work_list_origin[i][1])

work_list_origin

total = []

def todo_list(lst):
    for i in lst:
        if i[0] == "긴급" and i[1] == 2:
            total.append(i)
    for i in lst:
        if i[0] == "긴급" and i[1] == 3:
            total.append(i)
    for i in lst:
        if i[0] == "보통" and i[1] == 1:
            total.append(i)
    for i in lst:
        if i[0] == "보통" and i[1] == 3:
            total.append(i)
    for i in lst:
        if i[0] == "낮음" and i[1] == 1:
            total.append(i)
    for i in lst:
        if i[0] == "낮음" and i[1] == 2:
            total.append(i)

    return total

todo_list(work_list_origin)

